services:
  database:
    build:
      context: ./database
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=customer
    ports:
      - '4000:3306'
    networks:
      - myNetwork
  serverapi:
    build: .
    environment:
      API_PORT: 5000
    ports:
      - '5000:5000'
    networks:
      - servernetwork
    command: bash -c "npx prisma generate && npm run start"
    depends_on:
      - database
  webserver:
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - serverapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/ssl:/cert
      - ./html:/etc/nginx/html/
    networks:
      - servernetwork

networks:
  servernetwork:
    driver: bridge
