services:
  database-customer:
    build: .
    container_name: customer-database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=customer
    ports:
      - '4000:3306'
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
